
baseurl: "/ODS-Open-Raadsinformatie"
apiname: "Open Raadsinformatie"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: Open Raadsinformatie
    subnav:
      - title: Main
        path: /
  - title: Documentatie
    subnav:
      - title: Gebruik PeiltijdstipMaterieel
        path: /gebruikPeiltijdstipMaterieel
      - title: Overzicht Query-queryparameters
        path: /overzicht-queryparameters
  - title: Specificaties in concept
    subnav:
#      - title: Getting started
#        path: /getting-started
#      - title: User stories
#        url: https://vng-realisatie.github.io/IMWOZ-bevragingen/user-stories-prod
#        https://github.com/VNG-Realisatie/IMWOZ-bevragingen/issues?q=is%3Aissue+label%3A%22user+story%22
#        path: /user-stories
      - title: Open Raadsinformatie (swagger-ui)
        path: /ORI-swagger-ui
      - title: Open raadsinformatie (redoc)
        path: /ORI-redoc

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: VNG-Realisatie/jekyll-theme-vng-realisatie

github: VNG-Realisatie/ODS-Open-Raadsinformatie

theme: jekyll-theme-time-machine

project_name: /Open Raadsinformatie

standard_family: VNG Realisatie
